# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/openstackwang/x-search-app:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Stopping and removing old container ---"
            docker stop x-search || true
            docker rm x-search || true
            
            echo "--- Pulling the latest image ---"
            docker pull registry.cn-hangzhou.aliyuncs.com/openstackwang/x-search-app:${{ github.sha }}
            
            echo "--- Starting new container ---"
            docker run -d -p 3000:3000 --name x-search \
              -e NUXT_GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
              -e NUXT_SEARCH_ENGINE_ID=${{ secrets.SEARCH_ENGINE_ID }} \
              -e NUXT_BRAVE_API_KEY=${{ secrets.BRAVE_API_KEY }} \
              -e NUXT_GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              registry.cn-hangzhou.aliyuncs.com/openstackwang/x-search-app:${{ github.sha }}
            
            echo "Deployment complete."
